# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeprompt < Formula
  desc "K8S information in your prompt"
  homepage "https://github.com/jlesquembre/kubeprompt"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jlesquembre/kubeprompt/releases/download/0.2.0/kubeprompt_Darwin_x86_64.tar.gz"
    sha256 "1dadfe07eef88841edc0f6a533765bfa1df12c79e426b0b37f55ecd2fa7488f1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jlesquembre/kubeprompt/releases/download/0.2.0/kubeprompt_Linux_x86_64.tar.gz"
      sha256 "0c34cd817a6f4f382c8af1ccf9b7ccdff399ac74b30e59790bc3a45fe2f43e70"
    end
  end

  def install
    bin.install "kubeprompt"
  end

  test do
    system "#{bin}/kubeprompt -v"
  end
end
