# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeprompt < Formula
  desc "K8S information in your prompt"
  homepage "https://github.com/jlesquembre/kubeprompt"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jlesquembre/kubeprompt/releases/download/0.1.1/kubeprompt_Darwin_x86_64.tar.gz"
    sha256 "277a011b2c95b819f7ca58d1ad6fe86ddc3e10148a1a650ff535b27e8a169317"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jlesquembre/kubeprompt/releases/download/0.1.1/kubeprompt_Linux_x86_64.tar.gz"
      sha256 "0e43dcc0362531b61329f8b83666f3b61dcc5c423cee2d868ba655e7b639c59a"
    end
  end

  def install
    bin.install "kubeprompt"
  end

  test do
    system "#{bin}/kubeprompt -v"
  end
end
