# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeprompt < Formula
  desc "K8S information in your prompt"
  homepage "https://github.com/jlesquembre/kubeprompt"
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jlesquembre/kubeprompt/releases/download/0.3.0/kubeprompt_Darwin_x86_64.tar.gz"
    sha256 "bf86df7a3b63913592d85f7269268b9e9516487e38c25b0abdbfac6bd303a3e0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jlesquembre/kubeprompt/releases/download/0.3.0/kubeprompt_Linux_x86_64.tar.gz"
      sha256 "465fc7cd8cd345b1398b42ad8d28b6e5561b3b28b859747ab5b664b1c5ddc1c1"
    end
  end

  def install
    bin.install "kubeprompt"
  end

  test do
    system "#{bin}/kubeprompt -v"
  end
end
